version: '3'


services:

  
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    

  gateway:
    build: ./gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  usuarios-autenticacion-ms:
    build: ./usuarios-autenticacion-ms
    volumes:
      - ./usuarios-autenticacion-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}

  descripciones-imagenes-ms:
    build: ./descripciones-imagenes-ms
    volumes:
      - ./descripciones-imagenes-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
  
#   alertas-reportes-ms:
#     build: ./alertas-reportes-ms
#     volumes:
#       - ./alertas-reportes-ms/src:/usr/src/app/src
#     command: npm run start:dev
#     environment:
#       - PORT=3003
#       - DATABASE_URL=${DATABASE_URL}
#       - NATS_SERVERS=nats://nats-server:4222
